### ISSUE TITLE
Database Connections

### ISSUE THREAD

**Issue by michael34** [kochalex/caravel-docker#1]
I added:
RUN pip install psycopg2
to connect to postgresql-databases.
Maybe it would make sense to pip install some database connectors in the docker?

Regards

**Comment by michael34** [comment]
I ended up adding this after FROM:
RUN apt-get update
RUN apt-get install -y build-essential libssl-dev libffi-dev python-dev unixodbc-dev
RUN pip install psycopg2 
RUN pip install mysql-python
RUN pip install pyodbc
#Yes with have a lot of different databases unfortunately.

**Comment by kochalex** [comment]
:+1: You may want to take a look at https://github.com/amancevice/caravel, right now I was demoing this and haven't had the time to hook it up to real databases.

**Comment by michael34** [comment]
Looks good
